/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package test;

import dao.UsuarioDAO;
import javax.swing.JOptionPane;
import modelo.Usuario;

/**
 *
 * @author poletto
 */
public class cadastroFrame extends javax.swing.JFrame {

    /**
     * Creates new form testFrame
     */
    public cadastroFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        mailLabel = new javax.swing.JLabel();
        phoneLabel = new javax.swing.JLabel();
        mailField = new javax.swing.JTextField();
        birthLabel = new javax.swing.JLabel();
        cityField = new javax.swing.JTextField();
        stateLabel = new javax.swing.JLabel();
        neighborhoodField = new javax.swing.JTextField();
        cityLabel = new javax.swing.JLabel();
        neighborhoodLabel = new javax.swing.JLabel();
        rgLabel = new javax.swing.JLabel();
        addressLabel = new javax.swing.JLabel();
        cpfLabel = new javax.swing.JLabel();
        confirmButton = new javax.swing.JButton();
        lastnameField = new javax.swing.JTextField();
        nameField = new javax.swing.JTextField();
        lastnameLabel = new javax.swing.JLabel();
        nameLabel = new javax.swing.JLabel();
        birthField = new javax.swing.JFormattedTextField();
        phoneField = new javax.swing.JFormattedTextField();
        cpfField = new javax.swing.JFormattedTextField();
        stateComboBox = new javax.swing.JComboBox<>();
        addressField = new javax.swing.JTextField();
        rgField = new javax.swing.JFormattedTextField();
        cellphoneLabel = new javax.swing.JLabel();
        cellphoneField = new javax.swing.JFormattedTextField();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        mailLabel.setText("E-mail");

        phoneLabel.setText("Telefone");

        mailField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        mailField.setText("joaodasilva@email.com.br");
        mailField.setToolTipText("digite um e-mail válido");
        mailField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                mailFieldFocusGained(evt);
            }
        });

        birthLabel.setText("Data de nascimento");

        cityField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cityField.setText("São Paulo");
        cityField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cityFieldFocusGained(evt);
            }
        });

        stateLabel.setText("Estado");

        neighborhoodField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        neighborhoodField.setText("Centro");
        neighborhoodField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                neighborhoodFieldFocusGained(evt);
            }
        });

        cityLabel.setText("Cidade");

        neighborhoodLabel.setText("Bairro");

        rgLabel.setText("R.G.");

        addressLabel.setText("Endereço");

        cpfLabel.setText("CPF");

        confirmButton.setText("Confirmar Cadastro");
        confirmButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                confirmButtonActionPerformed(evt);
            }
        });

        lastnameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        lastnameField.setText("Silva");
        lastnameField.setToolTipText("Digite seu último nome");
        lastnameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                lastnameFieldFocusGained(evt);
            }
        });

        nameField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        nameField.setText("João");
        nameField.setToolTipText("Digite seu primeiro nome");
        nameField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                nameFieldFocusGained(evt);
            }
        });

        lastnameLabel.setText("Sobrenome");

        nameLabel.setText("Nome");

        try {
            birthField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##/##/####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        birthField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        birthField.setText("01/01/2000");
        birthField.setToolTipText("Digite sua data de nascimento");
        birthField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                birthFieldFocusGained(evt);
            }
        });

        try {
            phoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        phoneField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        phoneField.setText("(00) 1234-5678");
        phoneField.setToolTipText("Digite um número de telefone com DDD");
        phoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                phoneFieldFocusGained(evt);
            }
        });

        try {
            cpfField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("###.###.###-##")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cpfField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cpfField.setText("111.222.333-00");
        cpfField.setToolTipText("Digite seu CPF");
        cpfField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cpfFieldFocusGained(evt);
            }
        });

        stateComboBox.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Acre", "Alagoas", "Amapá", "Amazonas", "Bahia", "Ceará", "Distrito Federal", "Espírito Santo", "Goiás", "Maranhão", "Mato Grosso", "Mato Grosso do Sul", "Minas Gerais", "Paraná", "Paraíba", "Pará", "Pernambuco", "Piauí", "Rio de Janeiro", "Rio Grande do Norte", "Rio Grande do Sul", "Rondônia", "Roraima", "Santa Catarina", "Sergipe", "São Paulo", "Tocantins" }));
        stateComboBox.setToolTipText("");
        stateComboBox.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));

        addressField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        addressField.setText("Av. Paulista, 000");
        addressField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                addressFieldFocusGained(evt);
            }
        });

        try {
            rgField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###.###-#")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        rgField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        rgField.setText("00.111.999-0");
        rgField.setToolTipText("Digite somente os números anteriores ao Dígito um R.G. (Registro Geral) válido");
        rgField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                rgFieldFocusGained(evt);
            }
        });
        rgField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rgFieldActionPerformed(evt);
            }
        });

        cellphoneLabel.setText("Celular");

        try {
            cellphoneField.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("(##) ####-####")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }
        cellphoneField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        cellphoneField.setText("(00) 1234-5678");
        cellphoneField.setToolTipText("Digite um número de telefone com DDD");
        cellphoneField.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                cellphoneFieldFocusGained(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(confirmButton)
                .addGap(344, 344, 344))
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(rgLabel)
                    .addComponent(cpfLabel)
                    .addComponent(phoneLabel)
                    .addComponent(birthLabel)
                    .addComponent(mailLabel)
                    .addComponent(stateLabel)
                    .addComponent(neighborhoodLabel)
                    .addComponent(lastnameLabel)
                    .addComponent(nameLabel))
                .addGap(104, 104, 104)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(birthField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(nameField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lastnameField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(mailField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(neighborhoodField, javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(phoneField)
                    .addComponent(cpfField)
                    .addComponent(stateComboBox, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(rgField))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(cityLabel)
                    .addComponent(addressLabel)
                    .addComponent(cellphoneLabel))
                .addGap(37, 37, 37)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(cityField, javax.swing.GroupLayout.DEFAULT_SIZE, 148, Short.MAX_VALUE)
                    .addComponent(addressField)
                    .addComponent(cellphoneField))
                .addContainerGap(145, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(nameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(nameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lastnameField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lastnameLabel))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(rgLabel)
                    .addComponent(rgField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(cpfLabel)
                    .addComponent(cpfField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(23, 23, 23)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cellphoneLabel)
                        .addComponent(cellphoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(phoneLabel)
                        .addComponent(phoneField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(birthLabel)
                    .addComponent(birthField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(mailLabel)
                    .addComponent(mailField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(10, 10, 10)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(stateLabel)
                    .addComponent(cityLabel)
                    .addComponent(cityField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(stateComboBox, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(neighborhoodLabel)
                    .addComponent(neighborhoodField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(addressLabel)
                    .addComponent(addressField, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                .addComponent(confirmButton)
                .addGap(32, 32, 32))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mailFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_mailFieldFocusGained
        mailField.setText("");
    }//GEN-LAST:event_mailFieldFocusGained

    private void neighborhoodFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_neighborhoodFieldFocusGained
        neighborhoodField.setText("");
    }//GEN-LAST:event_neighborhoodFieldFocusGained

    private void cityFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cityFieldFocusGained
        cityField.setText("");
    }//GEN-LAST:event_cityFieldFocusGained

    private void nameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_nameFieldFocusGained
        nameField.setText("");
    }//GEN-LAST:event_nameFieldFocusGained

    private void lastnameFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_lastnameFieldFocusGained
        lastnameField.setText("");
    }//GEN-LAST:event_lastnameFieldFocusGained

    private void rgFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_rgFieldFocusGained
        rgField.setText("");
    }//GEN-LAST:event_rgFieldFocusGained

    private void cpfFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cpfFieldFocusGained
        cpfField.setText("");
    }//GEN-LAST:event_cpfFieldFocusGained

    private void phoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_phoneFieldFocusGained
        phoneField.setText("");
    }//GEN-LAST:event_phoneFieldFocusGained

    private void birthFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_birthFieldFocusGained
        birthField.setText("");
    }//GEN-LAST:event_birthFieldFocusGained

    private void addressFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_addressFieldFocusGained
        addressField.setText("");
    }//GEN-LAST:event_addressFieldFocusGained

    private void confirmButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_confirmButtonActionPerformed
        // TODO add your handling code here:
        Usuario usuarios = new Usuario();
        usuarios.setNome(nameField.getText());
        usuarios.setSobrenome(lastnameField.getText());
        usuarios.setRg(rgField.getText());
        usuarios.setCpf(cpfField.getText());
        usuarios.setTelefone(phoneField.getText());
        usuarios.setCelular(cellphoneField.getText());
        usuarios.setData(birthField.getText());
        usuarios.setEmail(mailField.getText());
        usuarios.setEstado((String) stateComboBox.getSelectedItem());
        usuarios.setCidade(cityField.getText());
        usuarios.setBairro(neighborhoodField.getText());
        usuarios.setEndereco(addressField.getText());
 
        if ((nameField.getText().isEmpty()) || (lastnameField.getText().isEmpty()) || (rgField.getText().isEmpty()) || (cpfField.getText().isEmpty()) || (phoneField.getText().isEmpty()) || (cellphoneField.getText().isEmpty()) || (birthField.getText().isEmpty()) || (mailField.getText().isEmpty()) || (cityField.getText().isEmpty()) || (neighborhoodField.getText().isEmpty()) || (addressField.getText().isEmpty())) {
            JOptionPane.showMessageDialog(null, "Algum campo se encontra vazio!");
        } else {
            UsuarioDAO dao = new UsuarioDAO();
            dao.adiciona(usuarios);
            JOptionPane.showMessageDialog(null, "Usuário " + nameField.getText() + " inserido com sucesso! ");
        }

        nameField.setText("");
        lastnameField.setText("");
        rgField.setText("");
        cpfField.setText("");
        phoneField.setText("");
        cellphoneField.setText("");
        birthField.setText("");
        mailField.setText("");
        cityField.setText("");
        neighborhoodField.setText("");
        addressField.setText("");

    }//GEN-LAST:event_confirmButtonActionPerformed

    private void cellphoneFieldFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_cellphoneFieldFocusGained
        cellphoneField.setText("");
    }//GEN-LAST:event_cellphoneFieldFocusGained

    private void rgFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rgFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_rgFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(cadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(cadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(cadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(cadastroFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new cadastroFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField addressField;
    private javax.swing.JLabel addressLabel;
    private javax.swing.JFormattedTextField birthField;
    private javax.swing.JLabel birthLabel;
    private javax.swing.JFormattedTextField cellphoneField;
    private javax.swing.JLabel cellphoneLabel;
    private javax.swing.JTextField cityField;
    private javax.swing.JLabel cityLabel;
    private javax.swing.JButton confirmButton;
    private javax.swing.JFormattedTextField cpfField;
    private javax.swing.JLabel cpfLabel;
    private javax.swing.JTextField lastnameField;
    private javax.swing.JLabel lastnameLabel;
    private javax.swing.JTextField mailField;
    private javax.swing.JLabel mailLabel;
    private javax.swing.JTextField nameField;
    private javax.swing.JLabel nameLabel;
    private javax.swing.JTextField neighborhoodField;
    private javax.swing.JLabel neighborhoodLabel;
    private javax.swing.JFormattedTextField phoneField;
    private javax.swing.JLabel phoneLabel;
    private javax.swing.JFormattedTextField rgField;
    private javax.swing.JLabel rgLabel;
    private javax.swing.JComboBox<String> stateComboBox;
    private javax.swing.JLabel stateLabel;
    // End of variables declaration//GEN-END:variables
}
